# Site Settings
title: Pogrebni Prevozi Edit Aljić
description: Profesionalni međunarodni prevoz pokojnika i repatrijacija umrlih iz EU u BiH, Srbiju, Crnu Goru i sve države Balkana. Dostupni 24/7, kompletna dokumentacija, 15+ godina iskustva.
url: https://pogrebni-prevozi.github.io
# Ako je sajt na https://username.github.io/ime-repozitorija, postavite baseurl na "/ime-repozitorija"
# Ako je sajt na https://username.github.io, ostavite baseurl prazan ""
baseurl: ""

# Contact Information
phone: "+386 70 443 005"
phone_display: "+386 70 443 005"
email: info@pogrebne-storitve-aljic.eu
website: https://pogrebne-storitve-aljic.eu
facebook: https://facebook.com/storitve.aljic
whatsapp: "38670443005"
viber: "38670443005"

# Company Information
company_name: Pogrebni Prevozi Edit Aljić S.P.
company_description: Profesionalni međunarodni prevoz pokojnika sa više od 15 godina iskustva u repatrijaciji umrlih iz EU u sve države Balkana.
established_year: 2008

# Address
address_street: Miklošičeva ulica 1c
address_city: Domžale
address_postal: 1230
address_country: Slovenija
address_country_code: SI

# SEO Settings
lang: bs
locale: bs_BA
author: Edit Aljić
keywords:
  - međunarodni prevoz pokojnika
  - repatrijacija umrlih
  - transport pokojnika iz EU
  - prevoz pokojnika iz Njemačke
  - prevoz pokojnika iz Austrije
  - prevoz pokojnika u BiH
  - prevoz pokojnika u Srbiju
  - pogrebni prevoz Balkan
  - leichenpass
  - prevoz umrlih osoba

# Google Analytics
google_analytics: G-7WMZFXTWKP

# Jekyll Settings
markdown: kramdown
permalink: /:categories/:title/
timezone: Europe/Ljubljana

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Edit Aljić

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - generate_routes.py

# SEO Tag Settings
social:
  name: Pogrebni Prevozi Edit Aljić
  links:
    - https://facebook.com/storitve.aljic
    - https://pogrebne-storitve-aljic.eu

# OpenGraph defaults
og_image: /assets/images/logo.png
